language: go

go:
  - 1.9.2

os:
  - osx

sudo: false

install:
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure
  - rm -fr vendor/github.com/github/hub && git clone https://github.com/github/hub.git vendor/github.com/github/hub

script:
  - make test-all
